name: flutter_ijkplayer
description: Flutter version of bilibili ijkplayer, supports common playback protocols, complete use documentation, easy to use.
version: 0.2.2
author: caijinglong<cjl_spy@163.com>
homepage: https://github.com/CaiJingLong/flutter_ijkplayer

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    androidPackage: top.kikt.ijkplayer
    pluginClass: IjkplayerPlugin
